version: "2"
services: 

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpt-codereviewer-web
    tty: true
    stdin_open: true
    volumes:
      - .:/gpt-codereviewer
    ports:
      - "8501:8501"